plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/girishiyer/Documents/SDE Projects : Side Business/My SDE Portfolio/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install && npx vite build"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]